### ISSUE TITLE
support TXT 

### ISSUE THREAD

**Issue by hi-glenn** [mwarning/SimpleDNS#2]
Could you implement TXT ？

I'm learning DNS program and reading your code.

I  add code to support TXT, but the answer can not be parsed successfully by dig.

**Comment by mwarning** [comment]
I do not plan to support txt. This should remain a rather simple example.

For TXT support, you can start to implement the case TXT_Resource_RecordType in encode_resource_records(). There you need to call put8bits for every character of the string. And do not forget to adjust rd_length.

Otherwise feel free to show me your progress and I can give it a quick look.

**Comment by hi-glenn** [comment]
Hello,

I have focked your repo and update it.

Would you have time to give it a quick look?

https://github.com/glennWang/SimpleDNS/blob/master/main.c#L599

**Comment by mwarning** [comment]
done - see the comments attached to the commit
